services:
  backschmiede-koelker_local:
    container_name: backschmiede-koelker_local
    image: node:20-bookworm
    working_dir: /app
    command: >
      sh -lc "
        [ -f .docker-npm.stamp ] || (
          npm ci --prefer-offline --no-audit --loglevel=warn &&
          npx prisma generate &&
          touch .docker-npm.stamp
        );
        npx prisma generate;
        npx prisma migrate dev;
        npx prisma db seed;
        npm run dev
      "
    env_file:
      - .env.local
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "500"
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "500"
    volumes:
      - ./:/app
      - ./uploads:/uploads
      - backschmiede-koelker_local_node_modules:/app/node_modules
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.backschmiede_local.rule=Host(`backschmiede-koelker.lan`)
      - traefik.http.routers.backschmiede_local.entrypoints=web
      - traefik.http.services.backschmiede_local.loadbalancer.server.port=3000
    networks:
      - web
      - db
    logging:
      driver: "local"
      options:
        max-size: "1m"
        max-file: "2"

volumes:
  backschmiede-koelker_local_node_modules:

networks:
  web:
    external: true
  db:
    external: true
